CREATE TABLE `sales` (
  `id` int(11) NOT NULL DEFAULT '0',
  `uuid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bike_branch` int(11) DEFAULT '0' COMMENT 'Map with branches',
  `bike_dealer` int(11) DEFAULT '0' COMMENT 'Map with bike_dealers',
  `bike_brand` int(11) DEFAULT '0' COMMENT 'Map with bike_brands',
  `bike_model` int(11) DEFAULT '0' COMMENT 'Map with bike_models',
  `bike_model_color` int(11) DEFAULT '0' COMMENT 'Map with bike_colors',
  `bike_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Bike' COMMENT 'Bike | Scooter',
  `bike_fuel_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Petrol' COMMENT 'Petrol | Electric | CNG |Diesel',
  `break_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Normal' COMMENT 'Normal | Disk',
  `wheel_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Alloy | Spoke',
  `dc_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Delievery Chalan',
  `dc_date` date DEFAULT NULL COMMENT 'Delievery Chalan Date',
  `vin_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '(Chasis Number) - Vichecal Identification number',
  `vin_physical_status` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Good ' COMMENT 'Good / Damaged / Not Recieved',
  `sku` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `hsn_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '87112029(',
  `engine_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `key_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `service_book_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tyre_brand_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tyre_front_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tyre_rear_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `battery_brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `battery_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purchase_invoice_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purchase_invoice_amount` decimal(10,2) DEFAULT '0.00',
  `purchase_invoice_date` date DEFAULT NULL,
  `bike_description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `pre_gst_amount` int(10) DEFAULT NULL,
  `gst_amount` int(10) DEFAULT NULL,
  `discount_price` int(10) DEFAULT NULL,
  `grand_total` int(10) DEFAULT NULL,
  `branch_id` int(11) DEFAULT '1',
  `bike_purchase_id` int(11) DEFAULT '0' COMMENT 'Map With Purchase Table',
  `customer_first_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_middle_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_last_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_father_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_address_line` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_state` int(11) DEFAULT NULL COMMENT 'Map with state table',
  `customer_district` int(11) DEFAULT NULL COMMENT 'Map with district table',
  `customer_city` int(11) DEFAULT NULL COMMENT 'Map with city table',
  `customer_zipcode` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_mobile_number` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_email_address` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Cash | Finance',
  `is_exchange_avaliable` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'No' COMMENT 'No | Yes',
  `hyp_financer` int(11) DEFAULT NULL,
  `hyp_financer_description` text COLLATE utf8mb4_unicode_ci,
  `purchase_visit_date` date DEFAULT NULL,
  `purchase_est_date` date DEFAULT NULL,
  `ex_showroom_price` decimal(10,2) DEFAULT '0.00',
  `registration_amount` decimal(10,2) DEFAULT '0.00',
  `insurance_amount` decimal(10,2) DEFAULT '0.00',
  `hypothecation_amount` decimal(10,2) DEFAULT '0.00',
  `accessories_amount` decimal(10,2) DEFAULT '0.00',
  `other_charges` decimal(10,2) DEFAULT '0.00',
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `active_status` tinyint(4) DEFAULT '1' COMMENT '0 => In Active, 1 => Active',
  `status` enum('open','close') COLLATE utf8mb4_unicode_ci DEFAULT 'open',
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
